Dash-Industry-Forum/livesim2

- CHANGELOG.md
- internal/version.go
- make `ato=inf` work, i.e. infinite availabilityTimeOffset
- list of complete MPD paths in /assets response
> Version 0.5.1

- CHANGELOG.md
- cmd/livesim2/app/config.go
- cmd/livesim2/app/configurl.go
- cmd/livesim2/app/configurl_test.go
- cmd/livesim2/app/handler_livesim_test.go
- cmd/livesim2/app/livempd.go
- cmd/livesim2/app/static/features.html
- cmd/livesim2/app/static/urlparams.html
With the new URL parameter `ltgt` it is possible to set the latency target and achieve much lower latencies in dash.js.
The min and max latencies are scaled as 75% and 200% of the target latency.
Fixes #25.
> Feature: new parameter ltgt to set latency target

- CHANGELOG.md
- cmd/livesim2/app/asset.go
- cmd/livesim2/app/livempd.go
- cmd/livesim2/app/livempd_test.go
- cmd/livesim2/app/static/features.html
- go.sum
Before now, the publish time was mapped directly to the UTC time which means that two requests for the same MPD would result in different values.
In this PR, this is changed so that `publishTime` reflects the last change of the MPD.
For an MPD using `SegmentTemplate with $Number$` this is typically
the `availabilityStartTime`, or or the start of an added period.
The case of `SegmentTimeline` is more complex. The algorithm used here is to
look at the availabilityTime of the last segment in the Manifest and use
that to define the publishTime. In case of a non-zero `availabilityTimeOffset` value,
the publishTime is shifted with the same amount to signal that the last segment in
the MPD is available that same amount earlier than its end time.
Fixes #28
> Publish time reflecting changes in MPD

- CHANGELOG.md
- cmd/livesim2/app/configurl.go
- cmd/livesim2/app/configurl_test.go
- cmd/livesim2/app/livempd.go
- cmd/livesim2/app/livempd_test.go
- cmd/livesim2/app/static/urlparams.html
- cmd/livesim2/app/strconv.go
New URL parameter utc_ allows for setting one or more UTCTiming methods, but also to specify none.
The head method does not need to be supported.
Solves #30.
> feat: support multiple UTC timing methods

- CHANGELOG.md
- README.md
- moved list URL parameters to [livesim2 wiki](https://github.com/Dash-Industry-Forum/livesim2/wiki/URL-Parameters)
- new URL parameter `periods` provides multiple periods (n <= 60 per hours, segment and period durations must be compatible)
- new URL parameter `segtimelinenr` turns on SegmentTimeline with `$Number$` addressing
- new URL parameter `mup` to set minimumUpdatePeriod in MPD
- new URL parameter `subsstppreg` can set vertical region
- new URL parameter `ltgt` sets latency target in milliseconds
- new URL parameter `utc` to set one, multiple, or zero UTCTiming methods
- new functionality to handle relative start and stop times by generating a Location element
- new config parameters `scheme` and `host` to be used in generated Location and BaseURL elements
- PublishTime now …
> docs: v0.6.0

- CHANGELOG.md
- cmd/livesim2/app/configurl.go
- cmd/livesim2/app/configurl_test.go
- cmd/livesim2/app/handler_livesim_test.go
- cmd/livesim2/app/livempd.go
Inserts supplemental property signalling period continuity if `continuous_1` URL parameter is set.
Resolves #44.
Setting `continuous_1 ` without `periods_x` will cause an error
> feat: configurable period continuity

- CHANGELOG.md
- cmd/livesim2/app/asset.go
- cmd/livesim2/app/livesegment.go
- cmd/livesim2/app/livesegment_test.go
Lets all segments (both from past and into future) available for availabilityTimeOffset=inf (only applies to SegmentTemplate with `$Number$`)
Needed for #59
> fix: ato_inf makes all segments available

- cmd/livesim2/app/handler_assets.go
JSON output of representations now include info from all segments. This becomes too much in AsssetInfo, so representation data is removed for now.
In the future, we should hav a nicer view of the assets.
> fix: remove representation data form assetInfo

- CHANGELOG.md
- cmd/livesim2/app/config.go
- cmd/livesim2/app/config_test.go
- cmd/livesim2/app/handler_assets.go
- cmd/livesim2/app/templates/assets.html
- cmd/livesim2/app/templates/assets_vod.html
Add links to start player directly from assets pages.
By default, the player links to go latest dash.js.
The scheme is automatically chosen to be http or https depending on the scheme of the server.
> feat: add play links to assets page with automatic scheme

- cmd/livesim2/app/configurl.go
The URLs to https://time.akamai.com/?isoms had http scheme. Now changed.
> fix: utc-timing URLs are now via https

- CHANGELOG.md
- cmd/livesim2/app/config.go
- cmd/livesim2/app/handler_assets.go
- cmd/livesim2/app/handler_urlgen.go
- cmd/livesim2/app/middleware.go
- cmd/livesim2/app/routes.go
It is hard to get a consistent playback of livesim2 content served via http for players with https scheme in their URL.
Therefore, this PR proxies the online player for the http case, while not touching the configured `playURL` for https.
Solves #106.
> Proxy online player for http

- cmd/livesim2/app/handler_livesim.go
- cmd/livesim2/app/handler_livesim_test.go
- cmd/livesim2/app/livempd_test.go
- cmd/livesim2/app/livesegment.go
- cmd/livesim2/app/livesegment_test.go
- cmd/livesim2/app/templates/welcome.html
- cmd/livesim2/app/timesubs_test.go
Add some tests for checking that the low-latency availability time is correct for manifests and segments.
> Check low-latency timeline availability

- cmd/livesim2/app/start.go
- pkg/logging/slog.go
Fix bug introduced when going from zero log to slog.
The status code and bytes written were not captured and written correctly.
> fix: status code and bytecount in request log

- .vscode/settings.json
- CHANGELOG.md
- cmd/livesim2/app/configurl.go
- cmd/livesim2/app/livempd.go
- cmd/livesim2/app/strconv.go
- cmd/livesim2/app/templates/urlgen.html
- New UTCTiming "modes" `httpisoms` and `httpxsdatems` for millisecond resolution
- Default UTCTiming signaling schemeIdUri set to "urn:mpeg:dash:utc:http-xsdate:2014"
Solves #141
> fix: default UTCTiming mode, and new millisecond versions

- cmd/livesim2/app/configurl.go
- cmd/livesim2/app/livempd.go
The UTCTiming formats for ISO and xsdate are very similar, so they now both deliver what is available from Akamai at the iso URL. That should fix the issue for dash.js as reported in #147.
> fix: set xsdate UTCTiming to ISO format

- CHANGELOG.md
- cmd/livesim2/app/livempd.go
- cmd/livesim2/app/livempd_test.go
Add contentType if absent from VoD asset and mimeType is one of "video/mp4", "audio/mp4", or "application/mp4"
> fix: derive and set contentType from mimeType if absent

- CHANGELOG.md
- cmd/livesim2/app/configurl.go
- cmd/livesim2/app/livempd.go
- cmd/livesim2/app/strconv.go
The UTCTiming schemes for "http-iso" and "http-head" missed the "http-" part.
Solves #162
> fix: correct schemes for UTCTiming

- cmd/livesim2/app/middleware.go
Add 
Access-Control-Allow-Methods and 
Access-Control-Allow-Headers
to make the ECCP key handling work.
Part 2 of #165
> fix: add CORS fields needed for ECCP json request

- CHANGELOG.md
- cmd/livesim2/app/handler_patch.go
- cmd/livesim2/app/handler_patch_test.go
- pkg/patch/patch.go
- pkg/patch/patch_test.go
Set expiration in HTTP response to originalPublishTime + TTL + 10s.
This is also the last time one can fetch the patch.
> fix: add Expires header to Patch response

- CHANGELOG.md
- internal/version.go
- MPD Patch functionality with new `/patch_ttl` URL configuration
- nowDate query parameter as an alternative to nowMS for MPD and patch
- Timed stpp subtitles EBU-TT-D linePadding
- Update dependencies
> docs: v1.3.0

- CHANGELOG.md
- cmd/livesim2/app/asset.go
- cmd/livesim2/app/livempd.go
- cmd/livesim2/app/livempd_test.go
MPDs were not updated and made available according to availabilityTimeOffset. Therefore, dash.js could not play low-latency content for SegmentTimeline as well as for SegmentTemplate with Number.
Solves #181
> fix: correct LL MPD availabilityTime for SegmentTimeline

- CHANGELOG.md
- cmd/livesim2/app/handler_index.go
- cmd/livesim2/app/handler_index_test.go
- cmd/livesim2/app/routes.go
- cmd/livesim2/app/templates/welcome.html
New endpoint /version will respond with the software version in JSON format
The software version is also present as an HTTP header in every response, so it is a bit superfluous to add an end point.
This should solve #185
> feat: new endpoint "/version"

- CHANGELOG.md
- cmd/livesim2/app/asset.go
- cmd/livesim2/app/livempd.go
- cmd/livesim2/app/livempd_test.go
If contentType and mimeType is not available on AdaptationSet level, the representations are scanned for the same field. If still not found, the codecs string is checked. This should allow for more content to be automatically detected.
The contentType is set on the adaptationSet level, so it should be visible in the output dynamic MPD.
Solves #197.
> fix: set contentType from mimeType or codecs

- cmd/cmaf-ingest-receiver/app/receiver.go
Fixes issue if directories has been cleaned so that the track directory is not present when a stream starts a second time.
> fix: create track directory for init segment, if not already available

- Dockerfile
Simple update to Dockerfile to insert Version (will be available in Web page, in server responser headers, and as a at the endpoint "/version".
> feat: improve Dockerfile to insert Version from github into livesim2

- CHANGELOG.md
- cmd/livesim2/app/templates/welcome.html
Landing page link to new Wiki page https://github.com/Dash-Industry-Forum/livesim2/wiki/Preparing-Content-for-livesim2
Solves #205 together  with wiki page.
> docs: new link on first page to Wiki page on preparing content

- CHANGELOG.md
- cmd/livesim2/app/asset.go
- cmd/livesim2/app/asset_test.go
Added a test that specifying endNumber limits the segments being loaded and used for looping.
> test: add test that endNumber shortens representation used

- .github/workflows/docker-publish.yml
- Dockerfile
Hi livesim2 team,
We've added a new GitHub action to create a Docker image. Additionally, we found an issue with the Go language image version. We fixed it by setting the version to 1.23, as it wasn't compatible with the latest version, and updated it accordingly.
Thank you!
Best regards
> Publish docker image with Github Action

- CHANGELOG.md
- internal/version.go
- Better logging when loading asset representation data
- Check that pre-encrypted content has the same duration for all representations
- Test that endNumber in SegmentTemplate will limit segments used
- Automatic build of Docker Images
- Pre-encrypted content is not re-fragmented, but left as it
- Dockerfile to insert version in binary (requires full repo or tag)
> docs: v1.5.1

- Makefile
I found `cmaf-ingest-receiver` is still missing in `Makefile` since it was introduced. 
So this fix added `cmaf-ingest-receiver` to `Makefile`.
> fix: add cmaf-ingest-receiver to Makefile

- cmd/livesim2/app/cmaf-ingester.go
After writing the first bytes from buffer, it doesn't "notify" the reader
and continue to write to the buffer without knowing buffer is consumed entirely or not.
The reader hence can send wrong data to receiver. With incorrect box size, it can hang forever.
`testpic` segment size is small (<65536), so it is not affected.
Big thanks to @nhannguyen700 for the fix.
> Fix: receiver hang indefinitely

- cmd/cmaf-ingest-receiver/app/channel.go
- cmd/livesim2/app/asset.go
This only support one timescale of AC-3/EC-3: 48kHz.
32kHz and 44.1kHz remain untouched.
> add ac-3/ec-3 support

- CHANGELOG.md
- cmd/livesim2/app/cmaf-ingester.go
- cmd/livesim2/app/cmaf-ingester_test.go
CMAF Ingest PUT of segments now use content-length, unless chunk duration is specified, in which case segments are pushed chunk by chunk as produced.
This solves #242.
> CMAF Ingest Content-Length

- CHANGELOG.md
- cmd/livesim2/app/configurl.go
- cmd/livesim2/app/handler_livesim.go
- cmd/livesim2/app/handler_livesim_test.go
- cmd/livesim2/app/handler_urlgen.go
- cmd/livesim2/app/livempd.go
- cmd/livesim2/app/strconv.go
- cmd/livesim2/app/templates/urlgen.html
- go.mod
- go.sum
> feat: basic annex I query string propagation

- cmd/livesim2/app/livempd.go
> fix: Drop ContentProtect if no LaURL for external DRM

- cmd/livesim2/app/timesubs.go
If segment is generated, e.g. `timesubsstpp`,
its each box is sent one by one
```
{..., "level":"WARN","msg":"Content-Length mismatch","ingester":4,"length":24,"contentLength":1797}
{..., "level":"WARN","msg":"Content-Length mismatch","ingester":4,"length":8,"contentLength":1797}
{..., "level":"WARN","msg":"Content-Length mismatch","ingester":4,"length":16,"contentLength":1797}
{..., "level":"WARN","msg":"Content-Length mismatch","ingester":4,"length":8,"contentLength":1797}
{..., "level":"WARN","msg":"Content-Length mismatch","ingester":4,"length":16,"contentLength":1797}
{..., "level":"WARN","msg":"Content-Length mismatch","ingester":4,"length":20,"contentLength":1797}
{..., "level":"WARN","msg":"Content-Length mismatch","ingester":4,"length":36,"contentLength":1797}
{..., …
```
> cmaf-ingest: fix generated segment is not sent at once

- .github/workflows/golangci-lint.yml
- .golangci.yml
- CHANGELOG.md
- cmd/cmaf-ingest-receiver/app/basicauth_test.go
- cmd/cmaf-ingest-receiver/app/channel.go
- cmd/cmaf-ingest-receiver/app/receiver.go
- cmd/cmaf-ingest-receiver/app/run_test.go
- cmd/cmaf-ingest-receiver/app/segtimelinegen.go
- cmd/dashfetcher/app/fetcher.go
- cmd/livesim2/app/api.go
- cmd/livesim2/app/asset.go
- cmd/livesim2/app/asset_test.go
- cmd/livesim2/app/cmaf-ingester.go
- cmd/livesim2/app/config.go
- cmd/livesim2/app/config_test.go
- cmd/livesim2/app/handler_laurl.go
- cmd/livesim2/app/handler_livesim_test.go
- cmd/livesim2/app/handler_patch_test.go
- cmd/livesim2/app/handler_urlgen.go
- cmd/livesim2/app/keys_test.go
- cmd/livesim2/app/livempd.go
- cmd/livesim2/app/livempd_test.go
- cmd/livesim2/app/livesegment.go
- cmd/livesim2/app/livesegment_test.go
- cmd/livesim2/app/timesubs.go
- cmd/livesim2/app/timesubs_test.go
- internal/mpddata.go
- pkg/patch/patch.go
- pkg/patch/patch_test.go
Update to golangci-lint v2 and fixed remarks
* neglected return values
* better loop conditions
* too long lines
> refactor: update to golangci-lint v2 and fix remarks
