Dash-Industry-Forum/livesim2

CHANGELOG.md
cmd/livesim2/app/routes.go

feat: HTTP redirect of /livesim and /dash/vod for livesim1 compatibility

---

cmd/livesim2/app/configurl.go
cmd/livesim2/app/handler_index.go
cmd/livesim2/app/handler_livesim.go
cmd/livesim2/app/livempd.go
cmd/livesim2/app/livempd_test.go

fix: fix use of configured or automatic scheme://host everywhere

---

cmd/livesim2/app/routes.go

fix: add livesim-chunked redirect

---

CHANGELOG.md
cmd/livesim2/app/asset.go
cmd/livesim2/app/handler_assets.go
cmd/livesim2/app/handler_index.go
cmd/livesim2/app/routes.go
cmd/livesim2/app/templates/assets.html
cmd/livesim2/app/templates/assets_vod.html
cmd/livesim2/app/templates/welcome.html
cmd/livesim2/app/templates_test.go
cmd/livesim2/app/testdata/assets/testpic_2s/Manifest.mpd
cmd/livesim2/app/testdata/assets/testpic_2s/Manifest_imsc1.mpd
cmd/livesim2/app/testdata/assets/testpic_2s/Manifest_thumbs.mpd
cmd/livesim2/app/testdata/assets/testpic_8s/Manifest.mpd
internal/mpddata.go

Update of welcome and assets pages using pico css.
Also extract asset information from ProgramInformation in DASH MPD and provide information about loop duration and other things.

feat: Much better information page and lists of assets

---

CHANGELOG.md
internal/version.go

Version v0.7.0 documentation

---

CHANGELOG.md
cmd/livesim2/app/prometheus.go

feat: Prometheus counters and histograms for request timing

---

CHANGELOG.md
cmd/livesim2/app/middleware.go

feat: send Timing-Allow-Origin in all responses

---

.vscode/settings.json
CHANGELOG.md
cmd/livesim2/app/config.go
cmd/livesim2/app/handler_index.go
cmd/livesim2/app/handler_livesim.go
cmd/livesim2/app/middleware.go
cmd/livesim2/app/templates/welcome.html

- CORS header for private network
- added muted=true to default playURL
- HTTP 410 Gone response for segments before timeShiftBufferDepth
- limited methods in OPTIONS response

Minor fixes

---

CHANGELOG.md
cmd/livesim2/app/routes.go
cmd/livesim2/app/server.go

feat: add /debug/pprof entry for profiling

---

CHANGELOG.md
cmd/livesim2/app/configurl.go
cmd/livesim2/app/configurl_test.go
cmd/livesim2/app/handler_livesim.go
cmd/livesim2/app/handler_urlgen.go
cmd/livesim2/app/livempd.go
cmd/livesim2/app/strconv.go
cmd/livesim2/app/templates/urlgen.html

feat: traffic pattern intervals with multiple base urls

---

CHANGELOG.md
cmd/livesim2/app/configurl.go
cmd/livesim2/app/livempd.go
cmd/livesim2/app/strconv.go
cmd/livesim2/app/templates/urlgen.html

feat: UTC timing "method" keep leaves VoD input values untouched

---

CHANGELOG.md
internal/version.go

- Add extra CORS headers to fix ECCP key request

doc: v1.2.2

---

CHANGELOG.md
cmd/livesim2/app/templates/stpptime.xml
cmd/livesim2/app/templates_test.go
cmd/livesim2/app/timesubs_test.go

fix: move the line padding element to a higher level style

---

pkg/patch/patch.go
pkg/patch/patch_test.go
pkg/patch/testdata/multiperiod_1.mpd
pkg/patch/testdata/multiperiod_2.mpd
pkg/patch/testdata/multiperiod_patch.mpp

This PR makes the difference work for the case where Periods and other elements are removed and inserted.
Fixes #177.

fix: handle multi-period MPDs properly

---

CHANGELOG.md
pkg/patch/patch.go
pkg/patch/patch_test.go
pkg/patch/testdata/segtimeline_multiper_after_full_min.mpd
pkg/patch/testdata/segtimeline_multiper_full_min.mpd
pkg/patch/testdata/segtimeline_multiper_patch_after_full_min.mpp

Resolves issue #189 and Slack issue reported by @dsilhavy

fix: multiperiod MPD patch response at new period start

---

CHANGELOG.md
cmd/livesim2/app/livempd.go
cmd/livesim2/app/livempd_test.go

fix: publishTime for multiperiod MPD

---

CHANGELOG.md
internal/version.go

- More error logging for segment generation.
- New endpoint /version responds with livesim2 version
- Some more links in the Welcome page
- fix patch response for multiperiod segment-timeline
- fix publishTime for multiperiod SegmentTemplate with Number

docs: v1.4.0

---

CHANGELOG.md
cmd/livesim2/app/livempd.go
cmd/livesim2/app/livempd_test.go
internal/version.go

Solves #193 and prepares for v1.4.1.

v1.4.1 with fix for multiperiod publishTime

---

CHANGELOG.md
cmd/livesim2/app/config.go
cmd/livesim2/app/ipreqlimit.go
cmd/livesim2/app/ipreqlimit_test.go
cmd/livesim2/app/start.go

New option --whitelistblocks for unlimited number of requests t…o some CIDR blocks
Solves #214

feat: whitelistblocks option

---

CHANGELOG.md
cmd/livesim2/app/livempd.go
cmd/livesim2/app/livempd_test.go
cmd/livesim2/app/testdata/assets/testpic_2s/Manifest_endNumber.mpd

Remove endNumber from all live MPD output.
Fixes #235

fix: issue #235 - endNumber in live MPD

---

CHANGELOG.md
cmd/cmaf-ingest-receiver/app/run.go
cmd/livesim2/app/middleware.go

Fix #251 by adding CORS header `Access-Control-Expose-Headers: "*"`

Expose Date header via CORS

---

CHANGELOG.md
Makefile
README.md
cmd/livesim2/app/livempd.go
cmd/livesim2/app/livempd_test.go
go.mod
go.sum

Upgraded dash-mod to v0.13.0 and fixed the issues due to new structures.
Also improved the Makefile when it comes to pre-commit

feat: update dash-mpd to v0.13.0 and improve Makefile
